### ISSUE TITLE
Q: Sharing a link to the 30th, 60th, 90th ckpts?

### ISSUE THREAD

**Issue by philferriere** [frederick0329/TracIn#4]
Hi @frederick0329 !

I was wondering if you had considered sharing the 30th, 60th, and 90th Resnet 50 checkpoints you are using in the notebook. Without them, like karasepid in another issue/thread, I'm sometimes confused about the shape of some of the variables/fields used. If the checkpoints were made available, then it would be straightforward for us to just step through the notebook code and print out those shapes.

Could the checkpoints perhaps be shared from a Google drive, or whatever online storage works best for you?

Thanks for considering this request!

Best regards, -- Phil

**Comment by frederick0329** [comment]
I'm really sorry philferriere@. Checkpoint release requires Google's legal approval and I don't think I will be able to do that. To validate the shapes, I think you can simply comment out weight loading and use 3 random inits.

**Comment by philferriere** [comment]
No worries, @frederick0329 .

Using 3 random inits is exactly what I've been doing to familiarize myself with the notebook code. The results are (obviously) meaningless but I am at least able to confirm tensor shapes.

Thank you for sharing the rational for not distributing the checkpoints though.
