### ISSUE TITLE
Efficint subset selection

### ISSUE THREAD

**Issue by diff7** [frederick0329/TracIn#7]
Hi, 
thank you for a great work.

I was wondering.
Have you tried using influence scores to select most influential data points to reduce training set?

Thank you!

**Comment by frederick0329** [comment]
No. We did try removing ~5% high-influential (high self influence, potentially mislabeled) data hoping to remove mislabeled data and it didn't hurt performance much (not cleaning the eval set).  However, we were looking for an improvement.

**Comment by diff7** [comment]
Hi, got it!

Thank you for your reply!
